apiVersion: v1alpha
kind: cypress
defaults:
  mode: sauce
sauce:
  region: pk-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    # build: Github Run $GITHUB_RUN_ID
cypress:
  version: 8.3.1 # See https://docs.saucelabs.com/dev/cli/saucectl/#supported-frameworks-and-browsers for a list of supported versions.
  configFile: "cypress.json"
